-   id: typstyle
    name: typstyle
    description: 'Format files with typstyle'
    entry: typstyle
    language: rust
    'files': \.typ$
    args: ["-i"]
    require_serial: false
    additional_dependencies: ["cli:typstyle:0.13.7"]
    minimum_pre_commit_version: '0'
